In [6]:
import random
import time
import numpy as np
a=[]
for i in range(10000000):
    a.append(random.random())

t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t3 = time.time()
sum2 = np.sum(b)
t4 = time.time()

print('%s = %lf' %(type(a), (t2-t1)))
print('%s = %lf' %(type(b), (t3-t2)))

<class 'list'> = 0.034092
<class 'numpy.ndarray'> = 0.255152


In [10]:
# create array methods
temp = [1,2,3,4,5,6,7,8,9]
arr1 = np.array(temp)
print(type(arr1))
print(arr1)


arr2 = np.array([4,24,2,2,2,3,4])
print(type(arr2))
print(arr2)

arr3 = np.array(range(5))
print(type(arr3))
print(arr3)

arr4 = np.arange(0,10,3)
print(type(arr4))
print(arr4)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 4 24  2  2  2  3  4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 3 6 9]


In [12]:
list1 = [[1,2],[3,4],[5,6]]
twoDimension = np.array(list1)
print(twoDimension.ndim)
print(twoDimension.shape)
print(twoDimension.size)

2
(3, 2)
6


In [13]:
t = np.arange(24).reshape(4,6)
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
